config/routes.rb
Seatyourself2::Application.routes.draw do
  # get "reservations/show"
  # get "reservations/new"
  # get "reservations/create"
  # get "reservations/edit"
  # get "reservations/destroy"
  # # get "sessions/new"
  # get "sessions/create"
  # get "sessions/destroy"
  # get "users/new"
  # get "users/create"
  resources :restaurants do
  	resources :reservations, :except => [:index]

  end


  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user

	validates :restaurant, presence: true
	validate :availability

	private
	def availability #only want to do something when a customer validation is false
		if !restaurant.availability(party_size, party_time)
			errors.add(:base, "restaurant is full, go away!") 
		end
	end	
end

#know an object is valid if the errors array is empty. If the error array is empty,... 
#...if there is one error it's invalid.
#validations run on save, create, and update_attributes; if there is an error, it will be added to the errors array. 
# Then, inspects the array. False means there are errors and the object does not get saved to the database.

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, :through => :reservations

	validates :name, :address, :phone, :capacity, :presence => true
	def availability(party_size, party_time)
		reserve_size = reservations.where(party_time: party_time).sum(:party_size)
		reserve_size + party_size <= capacity
	end

end

# For when I want to validate Datetime
# class MyModel < ActiveRecord::Base
#   validate :mydate_is_date?

#   private

#   def mydate_is_date?
#     if !mydate.is_a?(Date)
#       errors.add(:mydate, 'must be a valid date') 
#     end
#   end
# end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reservations
	has_many :restaurants, :through => :reservations
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  helper_method :current_user
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user_id = current_user.id

    if @reservation.save
      redirect_to restaurants_path, notice: "Reservation created successfully"

    else
      redirect_to restaurants_path, notice: "Reservation not created"
      # render :controller => :restaurants, :action => :show, :alert => "No Reservation Created"
      
    end
  end

  # def edit
  # end

  def destroy
      @reservation = Reservation.find(params[:id])
      @reservation.destroy
  end

private
  def reservation_params
    params.require(:reservation).permit(:restaurant_id, :party_size, :party_time)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:show]
	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])

		if current_user
			@reservation = @restaurant.reservations.build
		end
	end

	def new
		@restaurant = Restaurant.new
	end

	
	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)

		if @restaurant.save
			redirect_to restaurants_path 
		
		else 
			render :new
		end
	end


	def update
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update_attributes(restaurant_params)
			redirect_to @restaurant

		else 
			render :edit
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurants_path
	end

private
		def restaurant_params
		params.require(:restaurant).permit(:name, :address, :phone, :capacity, :menu)
		end
end

    

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to restaurants_path, :notice => "Logged in!"
		else
			flash.now[:alert] = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to restaurants_path, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to restaurants_path, :notice => "Signed Up!"
  	else
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Seatyourself2</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>

	<% if flash[:alert] %>
	<p id="alert"><%= flash[:alert] %></p>
	<% end %>

	<%= yield %>

	<p class="userinfo">
		<% if current_user %>
		Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>

		<% else %>
		<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
		<% end %>

	</p>

</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |form| %>
<% if @restaurant.errors.any? %>
	<div id="error_explanation" >
		<h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>

		<ul>
			<% @restaurant.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<p>
		<%= form.label :name %> <br>
		<%= form.text_field :name %>
	</p>

	<p>
		<%= form.label :address %> <br>
		<%= form.text_field :address %>
	</p>

	<p>
		<%= form.label :phone %> <br>
		<%= form.text_field :phone %>
	</p>

	<p>
		<%= form.label :capacity %> <br>
		<%= form.text_field :capacity %>
	</p>

	<p>
		<%= form.label :menu %> <br>
		<%= form.text_field :menu %>
	</p>

	<p>
		<%= form.submit "Save" %> <br>
	</p>
	
<%end%>

app/views/restaurants/edit.html.erb
<h1> Edit Restaurant </h1>

<%= render "form" %>

<%= link_to "Back", @restaurant %>

app/views/restaurants/index.html.erb
<h1> Restaurants </h1>

<%= link_to "Add a Restaurant", new_restaurant_path %>

<% @restaurants.each do |restaurant| %>

<div class="restaurant list">
	<h5>
		Name: <%= link_to restaurant[:name], restaurant_path(restaurant) %>
	</h5>
	
	<ul>
		<li>
			Address: <%= link_to restaurant[:address], restaurant_path(restaurant) %>
		</li>

		<li>
			Phone: <%= link_to restaurant[:phone], restaurant_path(restaurant) %>
		</li>
	
		<li>
			Capacity: <%= link_to restaurant[:capacity], restaurant_path(restaurant) %>
		</li>
	
		<li>
			Menu: <%= link_to restaurant[:menu], restaurant_path(restaurant) %>
		</li>
	</ul>

</div>

<% end %>

app/views/restaurants/new.html.erb
<h1> Add a Restaurant </h1>

<%= render "form" %>

<%= link_to "Back", restaurants_path %>

app/views/restaurants/show.html.erb
<%= link_to "Back to Restaurants", restaurants_path %> | 
<%= link_to "Edit", edit_restaurant_path(@restaurant) %> |
<%= link_to "Delete", @restaurant, :confirm => "Are you sure you want to delete this product?", :method => :delete %>

<p>
	<ul>
		<li> Name: <%= @restaurant[:name] %> </li>
		<li> Address: <%= @restaurant[:address] %> </li>
		<li> Phone: <%= @restaurant[:phone] %> </li>
		<li> Capacity: <%= @restaurant[:capacity] %> </li>
		<li> Menu: <%= @restaurant[:menu] %> </li>
	</ul>
</p>

<% if current_user %>

	<h3> Current Reservations </h3>
		
	<% @restaurant.reservations.each do |reservation| %>
	<p>
		<p>
			<ul>
				<li> # of Guests: <%= reservation.party_size %> </li>
				<li> Made on: <%= reservation.created_at %> </li>
				
				<li><% if reservation.user != nil %>
    				 Made by: <%= reservation.user.email %> </li>
			</ul>
		</p>	

		 <%end%>
		<% end %>
	<%end%>
	

<h4> Create a New Reservation </h4>
<%= form_for([@restaurant, @reservation]) do |form| %>
	<% if @reservation.errors.any? %>
		<div id="error_explanation" >
			<h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this reservation from being saved: </h2>

		<ul>
			<% @reservation.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


	<p>
		<%= form.label :party_size %> <br>
		<%= form.number_field :party_size %>
	</p>

	<p>
		<%= form.label :party_time %> <br>
		<%= form.datetime_select :party_time %>
	</p>

	<div class="actions">
		<p>
			<%= form.submit "Save" %> <br>
		</p>
	</div>	
<%end%>

<% else %>

<p> Please <%= link_to "log in", new_session_path %> to add a reservation. </p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="error_messages">
		<h2> Form is invalid </h2>

		<ul>
			<% for message in @user.errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="field">
	<%= f.label :email %><br/>
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %><br/>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation %><br/>
	<%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>

<% end %>